### ISSUE TITLE
[smart contracts] implement the uncensorable state channel

### ISSUE THREAD

**Issue by NicoSerranoP** [State-Channel-4/backend#9]
Implement this: [https://hackmd.io/@2y-oUv8rRpi6mYk9sSHOcw/BkWjEV5O2](https://hackmd.io/@2y-oUv8rRpi6mYk9sSHOcw/BkWjEV5O2)

The smart contract distribution and architecture is here: [https://www.figma.com/file/fVNtk4IxFvwGsaWJLSHjQd/Channel4Contract.sol?type=whiteboard&node-id=0%3A1&t=NkDONU2w5wtdCEdk-1](https://www.figma.com/file/fVNtk4IxFvwGsaWJLSHjQd/Channel4Contract.sol?type=whiteboard&node-id=0%3A1&t=NkDONU2w5wtdCEdk-1)

**Comment by NicoSerranoP** [comment]
Related to #15. Jack is already working on it

**Comment by hackertron** [comment]
@NicoSerranoP This can be closed now I think right ?

**Comment by NicoSerranoP** [comment]
> @NicoSerranoP This can be closed now I think right ?

Yes! : 🥳
